# Generated by Django 5.2.4 on 2025-07-15 15:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchasereturn_purchasereturnitem_salereturn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فئة مصروف',
                'verbose_name_plural': 'فئات المصروفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RevenueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فئة إيراد',
                'verbose_name_plural': 'فئات الإيرادات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=20, unique=True, verbose_name='رقم المرجع')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المصروف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('expense_type', models.CharField(choices=[('purchase', 'مشتريات'), ('operational', 'تشغيلية'), ('administrative', 'إدارية'), ('marketing', 'تسويقية'), ('maintenance', 'صيانة'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع المصروف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('bank_transfer', 'تحويل بنكي'), ('credit_card', 'بطاقة ائتمان'), ('check', 'شيك'), ('other', 'أخرى')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المورد')),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الإيصال')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('purchase_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_record', to='inventory.purchaseinvoice', verbose_name='فاتورة المشتريات')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.expensecategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=20, unique=True, verbose_name='رقم المرجع')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإيراد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('revenue_type', models.CharField(choices=[('sale', 'مبيعات'), ('service', 'خدمات'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع الإيراد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('bank_transfer', 'تحويل بنكي'), ('credit_card', 'بطاقة ائتمان'), ('check', 'شيك'), ('other', 'أخرى')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم العميل')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('sale_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_record', to='inventory.saleinvoice', verbose_name='فاتورة المبيعات')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.revenuecategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'إيراد',
                'verbose_name_plural': 'الإيرادات',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
